## Ejercicios de NumPy

1. Importa la librería de NumPy.

In [2]:
import numpy as np

2. Crea un array de 1 dimension y 10 elementos.

In [3]:
# Utilizo el método arange() porque me crea un array unidimensional.
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [4]:
# Primero creo una lista vacía donde se van a añadir los valores nuevos. 
array_nuevo = []

# Después, con un for itero por cada elemento del primer array para reemplazar esos valores.
# Si se pueden dividir entre 2 son pares y si no, son impares: con el método de listas append() añado ese valor a la lista vacía que he creado.
for num in array:
    if num % 2 == 0:  
        array_nuevo.append('par')
    else: 
        array_nuevo.append('impar')

In [5]:
# Convierto la lista en la que se han añadido los elementos en un array.
np.array(array_nuevo)

array(['par', 'impar', 'par', 'impar', 'par', 'impar', 'par', 'impar',
       'par', 'impar'], dtype='<U5')

In [16]:
# Otra forma de hacerlo con un np.where, si no se puede dividir entre 2 es impar y si no, es par.
array_cambiado = np.where(array % 2 !=0, 'impar', 'par')
array_cambiado

array(['par', 'impar', 'par', 'impar', 'par', 'impar', 'par', 'impar',
       'par', 'impar'], dtype='<U5')

4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [6]:
# Con el método reshape() cambio la forma del array sin cambiar sus datos.
array_nuevo = np.reshape(array_nuevo,(2,5))
array_nuevo

array([['par', 'impar', 'par', 'impar', 'par'],
       ['impar', 'par', 'impar', 'par', 'impar']], dtype='<U5')

5. Extrae los elementos comunes de los siguientes arrays

In [7]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [8]:
# Utilizo el método np.intersect1d() para encontrar los elementos comunes: son el 2 y el 4.
np.intersect1d(array1, array2)

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [9]:
# Utilizo el método np.setdiff1d() para que me encuentre cuales son los elementos que están en el array1, pero no en el array2. 
# En este caso, la posición de los arrays en la sintaxis es importante.
np.setdiff1d(array1, array2)

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [20]:
# Utilizo el método np.where, ya que me devuelve los índices donde los elementos son iguales, entre paréntesis pongo la condición.
np.where(array1 == array2)


(array([1, 3, 5, 7]),)

- En el índice 1 encontramos el nº 2.
- En el índice 3 encontramos el nº 2.
- En el índice 5 encontramos el nº 4.
- En el índice 7 encontramos el nº 4.

8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [40]:
# Utilizo el método np.random.randint() que nos devuelve un array de x dimensiones con nº enteros aleatorios porque tenemos que especificar
# entre que números queremos que estén (0, 50).
array3 = np.random.randint(0, 50, (3,5))
array3

array([[ 7, 37, 30, 28, 15],
       [40, 38, 42, 18, 23],
       [12, 21, 31, 25,  9]])

arr3[(arr3 < 10) | (arr3 > 40)]

In [44]:
# Utilizo el operador | para que se cumplan las condiciones.
array3[(array3 < 10) | (array3 > 40)]

array([ 7, 42,  9])

9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [45]:
# Utilizo el método np.random.uniform() porque genera un array con valores aleatorios uniformes. En el parámetro size indico el taño del array.
# Para que no sean números con muchos decimales, utilizo el método round() para que redondee el nº a dos decimales.
np.random.uniform(5, 10, (5, 3)).round(2)

array([[8.86, 8.99, 7.59],
       [8.37, 7.15, 6.28],
       [7.76, 5.04, 5.42],
       [7.53, 5.18, 9.89],
       [7.31, 5.21, 8.31]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20.

In [14]:
# Utilizo de nuevo el método np.random.randint().
array4 = np.random.randint(1, 20, (2,4,7))
array4

array([[[ 8,  7,  7, 19,  4,  2, 12],
        [ 6,  1, 15, 18,  4, 19,  2],
        [12, 13, 17, 18, 10,  3, 18],
        [15, 13, 18,  1,  3, 18,  8]],

       [[14,  6,  3,  9, 12, 18,  8],
        [ 1,  2, 16,  1, 14, 10, 19],
        [15, 16, 13,  1, 12, 19, 13],
        [10,  9, 14, 11, 13,  6,  7]]])

Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [15]:
# Utilizo el método np.transpose cambio las dimensiones el array. 
# Le paso una tupla indicando los ejes y la posición en la que los quiero: el 4 está en el índice 1, el 7 en el índice 2 y el 2 en el índice 0.
array5 = np.transpose(array4, (1,2,0))
array5

array([[[ 8, 14],
        [ 7,  6],
        [ 7,  3],
        [19,  9],
        [ 4, 12],
        [ 2, 18],
        [12,  8]],

       [[ 6,  1],
        [ 1,  2],
        [15, 16],
        [18,  1],
        [ 4, 14],
        [19, 10],
        [ 2, 19]],

       [[12, 15],
        [13, 16],
        [17, 13],
        [18,  1],
        [10, 12],
        [ 3, 19],
        [18, 13]],

       [[15, 10],
        [13,  9],
        [18, 14],
        [ 1, 11],
        [ 3, 13],
        [18,  6],
        [ 8,  7]]])